name = "turnstile-contact-worker"
workers_dev = true

compatibility_date = "2022-09-26"

main = "src/idx.mjs"

[vars]
TURNSTILE_SITE_KEY = "1x00000000000000000000AA"
TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"
EMAIL_ADDRESS = "example@example.com"
